# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
defaults: &top
  docker: 
    - image: circleci/node:13.8.0
    
jobs:
  build:
    <<: *top
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *top
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    <<: *top
    steps:
      - checkout
      - run: npm audit
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
